design_system_file: design-system.yaml
main:
  - id: screen01
    type: screen
    spec_file: features/screen01/screen01.spec.yaml
    view_file: features/screen01/screen01.view.yaml
    test_file: features/screen01/screen01.test.yaml
app_file: app.yaml
routes:
  - path: /
    screen: screen01
